### ISSUE TITLE
System never starts a camera

### ISSUE THREAD

**Issue by TheBricktop** [keijiro/HandLandmarkBarracuda#1]
While the camera is set to the correct x y values the webcamtex is not receveing data.

**Comment by keijiro** [comment]
You have to clear the Dummy Image property of the Webcam Input component to use a real webcam device.

**Comment by keijiro** [comment]
Please note that you need a hand region detector (like [BlazePlam](https://github.com/keijiro/BlazePalmBarracuda)) to use the hand landmark detector properly. You can't do anything interesting only with this landmark model.

**Comment by keijiro** [comment]
I"m closing this issue now. Please feel free to reopen it for further problems.
